# Generated by Django 4.2.6 on 2023-11-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('colegiado', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=75)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
