# Generated by Django 4.2.6 on 2023-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('dpi', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombrepaciente', models.CharField(max_length=75)),
                ('fechanacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='medicos',
            name='colegiado',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidad',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
